fix line endings in swagger-ui.js
line endings were causing the zip file repository to fail to git init:

fatal: CRLF would be replaced by LF in coolstore-gw/src/main/resources/static/swagger-ui.js.

{{{

{
  "changed": true,
  "cmd": "mv /tmp/coolstore-gitD55jJw/coolstore-microservice-stable-ocp-3.9/* /tmp/coolstore-gitD55jJw
 rm -rf /tmp/coolstore-gitD55jJw/coolstore-microservice-stable-ocp-3.9
 git init
 git remote add origin http://gogs-cicd-demo.192.168.42.114.nip.io/team/coolstore-microservice.git
 git add . --all
 git config user.email \"rhdeveloper@redhat.com\"
 git config user.name \"rh-developer\"
 git commit -m \"Initial add\"
 git push -f http://team:team@gogs-cicd-demo.192.168.42.114.nip.io/team/coolstore-microservice.git master",
  "delta": "0:00:00.142002",
  "end": "2018-05-19 18:35:10.915118",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2018-05-19 18:35:10.773116",
  "stderr": "fatal: CRLF would be replaced by LF in coolstore-gw/src/main/resources/static/swagger-ui.js.
error: src refspec master does not match any.
error: failed to push some refs to 'http://team:team@gogs-cicd-demo.192.168.42.114.nip.io/team/coolstore-microservice.git'",
  "stderr_lines": [
    "fatal: CRLF would be replaced by LF in coolstore-gw/src/main/resources/static/swagger-ui.js.",
    "error: src refspec master does not match any.",
    "error: failed to push some refs to 'http://team:team@gogs-cicd-demo.192.168.42.114.nip.io/team/coolstore-microservice.git'"
  ],
  "stdout": "Initialized empty Git repository in /tmp/coolstore-gitD55jJw/.git/
# On branch master
#
# Initial commit
#
# Untracked files:
#   (use \"git add <file>...\" to include in what will be committed)
#
#\tREADME.md
#\tcart-service/
#\tcatalog-service/
#\tcoolstore-gw/
#\tcoolstore-ui/
#\tdocs/
#\tinventory-service/
#\topenshift/
#\tpricing-service/
#\trating-service/
#\treview-service/
#\tsso-service/
nothing added to commit but untracked files present (use \"git add\" to track)",
  "stdout_lines": [
    "Initialized empty Git repository in /tmp/coolstore-gitD55jJw/.git/",
    "# On branch master",
    "#",
    "# Initial commit",
    "#",
    "# Untracked files:",
    "#   (use \"git add <file>...\" to include in what will be committed)",
    "#",
    "#\tREADME.md",
    "#\tcart-service/",
    "#\tcatalog-service/",
    "#\tcoolstore-gw/",
    "#\tcoolstore-ui/",
    "#\tdocs/",
    "#\tinventory-service/",
    "#\topenshift/",
    "#\tpricing-service/",
    "#\trating-service/",
    "#\treview-service/",
    "#\tsso-service/",
    "nothing added to commit but untracked files present (use \"git add\" to track)"
  ]
}

}}}